### ISSUE TITLE
Examples not restoring window states or URLs.

### ISSUE THREAD

**Issue by eengoron** [electron-utils/electron-window-plus#2]
Hey Johnny -- 

I tried to run the examples on my end from your `examples` folder, and I can't seem to get window urls or user data to restore after I close and reopen the app on any of the examples. 

Are the examples in the repo supposed to restore the URL of windows on `ready`?

If so, are there any tips you can give me on how to make sure I've set up things correctly? Thanks!

**Comment by jwu** [comment]
Hi eengoron,

I've fix the problem by update the deps. It is because the profile didn't load correctly in last version. pls check my changes: https://github.com/electron-utils/electron-window-plus/commit/5050ec9f0c6278cdae9e23975a136262ed84b9a8
